server:
  port: 1997

spring:
  application:
    name: ADDRESS-SERVICE
    data:
      mongodb:
        database: springMicroService
        host: localhost
        port: 27017
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: locahost
