server :
  port : 1999

spring :
  application :
         name : API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CANDIDATE-SERVICE
          uri: http://localhost:1996
          predicates:
            - Path=/candidate/**
        - id: ADDRESS-SERVICE
          uri: http://localhost:1997
          predicates:
            - Path=/address/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: locahost

